In [2]:
import pandas as pd

# ONS

In [5]:
ons = pd.read_parquet("data/interim/load_clean.parquet")

In [6]:
print(ons.head())
print(ons.tail())

  subsystem_code subsystem           timestamp    load_mw  source_year
0             NE  NORDESTE 2022-01-01 00:00:00  10508.822         2022
1             NE  NORDESTE 2022-01-01 01:00:00  10598.654         2022
2             NE  NORDESTE 2022-01-01 02:00:00  10625.716         2022
3             NE  NORDESTE 2022-01-01 03:00:00  10583.828         2022
4             NE  NORDESTE 2022-01-01 04:00:00  10495.137         2022
      subsystem_code subsystem           timestamp    load_mw  source_year
41443             NE  NORDESTE 2026-09-23 19:00:00  15692.502         2026
41444             NE  NORDESTE 2026-09-23 20:00:00  15962.518         2026
41445             NE  NORDESTE 2026-09-23 21:00:00  16575.507         2026
41446             NE  NORDESTE 2026-09-23 22:00:00  16695.429         2026
41447             NE  NORDESTE 2026-09-23 23:00:00  16202.022         2026

In [18]:
ons.head()

  subsystem_code subsystem           timestamp    load_mw  source_year
0             NE  NORDESTE 2022-01-01 00:00:00  10508.822         2022
1             NE  NORDESTE 2022-01-01 01:00:00  10598.654         2022
2             NE  NORDESTE 2022-01-01 02:00:00  10625.716         2022
3             NE  NORDESTE 2022-01-01 03:00:00  10583.828         2022
4             NE  NORDESTE 2022-01-01 04:00:00  10495.137         2022

In [7]:
ons.info()

<class 'pandas.DataFrame'>
RangeIndex: 41448 entries, 0 to 41447
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subsystem_code  41448 non-null  string
 1   subsystem       41448 non-null  str
 2   timestamp       41448 non-null  datetime64[us]
 3   load_mw         41448 non-null  float64
 4   source_year     41448 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(1), str(1), string(1)
memory usage: 2.0 MB

In [9]:
anos = ons['source_year'].unique()
print(f"Anos disponíveis: {anos}")

Anos disponíveis: [2022 2023 2024 2025 2026]

In [10]:
print(ons.isna().sum())

subsystem_code    0
subsystem         0
timestamp         0
load_mw           0
source_year       0
dtype: int64

In [11]:
print(ons.duplicated().sum())

0

In [12]:
ons.describe()

                 timestamp       load_mw   source_year
count                41448  41448.000000  41448.000000
mean   2024-05-13 11:30:00  12580.532112   2023.885350
min    2022-01-01 00:00:00   7262.283000   2022.000000
25%    2023-03-08 17:45:00  11544.804750   2023.000000
50%    2024-05-13 11:30:00  12623.361500   2024.000000
75%    2025-07-19 05:15:00  13696.423000   2025.000000
max    2026-09-23 23:00:00  18156.972000   2026.000000
std                    NaN   1520.057541      1.367879

# INMET

In [13]:
inmet = pd.read_parquet("data/interim/weather_clean.parquet")

In [14]:
inmet.head()

,timestamp,region,precipitation_mm,pressure_station_hpa,pressure_max_hpa,pressure_min_hpa,global_radiation_kj_m2,temperature_c,dew_point_c,temperature_max_c,temperature_min_c,dew_point_max_c,dew_point_min_c,humidity_max_pct,humidity_min_pct,humidity_pct,wind_gust_ms,wind_speed_ms,wind_direction_deg,station_count
0,2022-01-01 00:00:00+00:00,NORDESTE,1.165217,974.582143,974.605357,973.880357,1.620000,23.971429,20.721569,24.460714,23.894643,20.936000,20.372000,82.680000,78.760000,82.392157,4.003704,1.503704,97.753149,144
1,2022-01-01 01:00:00+00:00,NORDESTE,0.339130,976.091379,976.155172,975.739655,68.233333,23.655172,20.926923,24.127586,23.581034,21.175472,20.639623,85.471698,81.981132,84.711538,4.121818,1.352727,104.333533,144
2,2022-01-01 02:00:00+00:00,NORDESTE,0.343478,973.700000,973.919298,973.631579,123.000000,23.119298,20.912245,23.491228,23.068421,21.048980,20.646939,87.208333,84.653061,86.937500,3.680000,1.287273,101.001139,144
3,2022-01-01 03:00:00+00:00,NORDESTE,0.097872,975.218966,975.636207,975.194828,457.171429,23.053448,20.966000,23.387931,22.996552,21.134000,20.800000,88.163265,85.959184,87.816327,3.430909,1.145455,96.908462,144
4,2022-01-01 04:00:00+00:00,NORDESTE,0.114894,973.732143,974.223214,973.712500,306.800000,22.785714,20.923913,23.053571,22.700000,21.095652,20.769565,88.777778,86.911111,88.444444,3.075472,1.056604,106.756377,144

In [15]:
inmet.tail()

,timestamp,region,precipitation_mm,pressure_station_hpa,pressure_max_hpa,pressure_min_hpa,global_radiation_kj_m2,temperature_c,dew_point_c,temperature_max_c,temperature_min_c,dew_point_max_c,dew_point_min_c,humidity_max_pct,humidity_min_pct,humidity_pct,wind_gust_ms,wind_speed_ms,wind_direction_deg,station_count
40891,2026-08-31 19:00:00+00:00,NORDESTE,0.0,976.298649,976.432432,976.137838,1206.631944,31.134211,16.507353,32.098684,30.676316,17.229412,15.919118,46.811594,42.318841,45.246377,7.819118,3.167647,102.857044,140
40892,2026-08-31 20:00:00+00:00,NORDESTE,0.0,976.643243,976.656757,976.270270,525.047945,30.077632,16.700000,31.346053,30.010526,17.145588,16.001471,49.434783,44.159420,48.652174,7.513235,3.005882,102.949787,140
40893,2026-08-31 21:00:00+00:00,NORDESTE,0.0,977.532857,977.540000,977.131429,80.918571,28.388889,16.889231,29.977778,28.368056,17.210606,16.425758,54.029851,48.402985,53.121212,6.564063,2.329687,100.969863,140
40894,2026-08-31 22:00:00+00:00,NORDESTE,0.0,978.015714,978.022857,977.528571,11.789474,27.111111,17.436923,28.431944,27.045833,17.555385,16.753846,58.575758,52.848485,58.363636,5.456250,2.184375,107.139521,140
40895,2026-08-31 23:00:00+00:00,NORDESTE,0.0,979.294118,979.295588,978.605882,15.588889,26.190000,17.876190,27.170000,26.148571,18.057143,17.304762,63.171875,58.109375,62.750000,5.508065,2.029032,107.810911,140

In [16]:
inmet.info()

<class 'pandas.DataFrame'>
RangeIndex: 40896 entries, 0 to 40895
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   timestamp               40896 non-null  datetime64[us, UTC]
 1   region                  40896 non-null  str
 2   precipitation_mm        40896 non-null  float64
 3   pressure_station_hpa    40896 non-null  float64
 4   pressure_max_hpa        40896 non-null  float64
 5   pressure_min_hpa        40896 non-null  float64
 6   global_radiation_kj_m2  40893 non-null  float64
 7   temperature_c           40896 non-null  float64
 8   dew_point_c             40896 non-null  float64
 9   temperature_max_c       40896 non-null  float64
 10  temperature_min_c       40896 non-null  float64
 11  dew_point_max_c         40896 non-null  float64
 12  dew_point_min_c         40896 non-null  float64
 13  humidity_max_pct        40896 non-null  float64
 14  humidity_min_pct        40896 non-null  float64
 15  humidity_pct            40896 non-null  float64
 16  wind_gust_ms            40896 non-null  float64
 17  wind_speed_ms           40896 non-null  float64
 18  wind_direction_deg      40896 non-null  float64
 19  station_count           40896 non-null  int64
dtypes: datetime64[us, UTC](1), float64(17), int64(1), str(1)
memory usage: 6.6 MB

In [17]:
inmet.isna().sum()

timestamp                 0
region                    0
precipitation_mm          0
pressure_station_hpa      0
pressure_max_hpa          0
pressure_min_hpa          0
global_radiation_kj_m2    3
temperature_c             0
dew_point_c               0
temperature_max_c         0
temperature_min_c         0
dew_point_max_c           0
dew_point_min_c           0
humidity_max_pct          0
humidity_min_pct          0
humidity_pct              0
wind_gust_ms              0
wind_speed_ms             0
wind_direction_deg        0
station_count             0
dtype: int64